# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: 编译->测试->上传代码报告

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: 设置jdk 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: 缓存Maven包
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
      - name: 编译测试
        run: mvn clean compile test install
      - name: 生成代码报告
        run: mvn cobertura:cobertura
      - name: 上传报告到 Codecov
        # You may pin to the exact commit or the version.
        # uses: codecov/codecov-action@239febf655bba88b16ff5dea1d3135ea8663a1f9
        uses: codecov/codecov-action@v1.0.15
        with:
          # User defined upload name. Visible in Codecov UI
          name: tulip
          # Repository upload token - get it from codecov.io. Required only for private repositories
          token: d1dcd713-454e-4559-b692-a538bd356484
